services:
  postgres:
    image: postgres:17
    container_name: secure-data-postgres
    environment:
      POSTGRES_DB: secure_data
      POSTGRES_USER: secure_user
      POSTGRES_PASSWORD: secure_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - secure_data_network

  postgres-replica1:
    image: postgres:17
    container_name: secure-data-postgres-replica1
    ports:
      - "5433:5432"
    volumes:
      - postgres_replica1_data:/var/lib/postgresql/data
      - ./docker/postgres/pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
    networks:
      - secure_data_network

  postgres-replica2:
    image: postgres:17
    container_name: secure-data-postgres-replica2
    ports:
      - "5434:5432"
    volumes:
      - postgres_replica2_data:/var/lib/postgresql/data
      - ./docker/postgres/pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
    networks:
      - secure_data_network

volumes:
  postgres_data:
  postgres_replica1_data:
  postgres_replica2_data:

networks:
  secure_data_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16